CREATE DATABASE IF NOT EXISTS ielts_ai;
USE ielts_ai;

DROP TABLE IF EXISTS answers;
DROP TABLE IF EXISTS questions;
DROP TABLE IF EXISTS exams;
DROP TABLE IF EXISTS exam_results;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY unique_email (email)
);

CREATE TABLE exam_results (
  id INT NOT NULL AUTO_INCREMENT,
  user_id INT DEFAULT NULL,
  reading FLOAT DEFAULT NULL,
  writing FLOAT DEFAULT NULL,
  listening FLOAT DEFAULT NULL,
  speaking FLOAT DEFAULT NULL,
  overall FLOAT DEFAULT NULL,
  feedback TEXT,
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  difficulty VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE exams (
  id INT NOT NULL AUTO_INCREMENT,
  user_id INT DEFAULT NULL,
  difficulty VARCHAR(20) DEFAULT NULL,
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE questions (
  id INT NOT NULL AUTO_INCREMENT,
  exam_id INT DEFAULT NULL,
  skill VARCHAR(20) DEFAULT NULL,
  question_text TEXT,
  PRIMARY KEY (id),
  FOREIGN KEY (exam_id) REFERENCES exams(id) ON DELETE CASCADE
);

CREATE TABLE answers (
  id INT NOT NULL AUTO_INCREMENT,
  question_id INT DEFAULT NULL,
  answer_text TEXT,
  score FLOAT DEFAULT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (question_id) REFERENCES questions(id) ON DELETE CASCADE
);
